### ISSUE TITLE
[Branch protection rule(s)] Enable restrictions for openms-docs branches

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#107]
1. Branch name pattern: `^(.*? )?(main|staging|develop)$(.*? )?` https://rubular.com/r/3vZ1rlUIskWqbP
2. PR specific
<img width="1308" alt="Screenshot 2022-06-17 at 7 49 39 PM" src="https://user-images.githubusercontent.com/4143778/174316725-315ec1bd-e5c6-4b2f-9844-89d3f3636973.png">

3. include administrators.
<img width="1278" alt="Screenshot 2022-06-17 at 7 53 37 PM" src="https://user-images.githubusercontent.com/4143778/174317460-d7cc1830-b59c-4ff0-a629-cf48542fb1ab.png">
 
Ref: https://github.com/OpenMS/OpenMS-docs/pull/97.

cc @jpfeuffer.

**Comment by timosachsenberg** [comment]
somehow only worked: ^(main|staging|develop)$ but should also be ok right?
update: no not even... seems branch protection rules don't take regex

**Comment by timosachsenberg** [comment]
will do 3 rules instead (as suggested on SO)

**Comment by timosachsenberg** [comment]
done

**Comment by tapaswenipathak** [comment]
> somehow only worked: ^(main|staging|develop)$ but should also be ok right?

shorter the better. https://rubular.com/r/m6mKN1shSYfBGC

> update: no not even... seems branch protection rules don't take regex

both should've worked: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#about-branch-protection-rules.

----

seems to work.

<img width="1405" alt="Screenshot 2022-06-18 at 8 30 39 AM" src="https://user-images.githubusercontent.com/4143778/174420159-b4e68585-b0b2-4406-9d2f-f850f4532225.png">

<img width="1217" alt="Screenshot 2022-06-18 at 8 31 07 AM" src="https://user-images.githubusercontent.com/4143778/174420176-0de3bbe2-e0ae-4a6d-9776-e60234877220.png">
