### ISSUE TITLE
remove TOPPAS

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-docs#132]
https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/tutorials-and-quickstart-guides/guides/user-quickstart-guide.html

- [ ] see also only links to utils documentation
- [ ] it still refers to TOPPAS. Should we just remove all the TOPPAS things?

## Read Existing Documentation

I have checked the following places for the error:

- [ ] [OpenMS Documentation Troubleshooting]()
- [ ] [OpenMS API Developer FAQs]()

## Create OpenMS Bug Report

I have created the bug report in OpenMS for any pipeline errors.

- [ ] [OpenMS Open Issues](https://github.com/OpenMS/OpenMS/issues)

## Description of the documentation bug

- [ ] I have attached screenshots of the incorrect documentation

## OpenMS Installation

- Version:

**Comment by ghost** [comment]
Yes all TOPPAS references should be removed, except for the message that says that it is deprecated.
