### ISSUE TITLE
Installation options on Linux

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#15]
I think we should reorder. Not sure how stable our debian packages are. They should be moved down.
Docker instructions need update.

**Comment by tapaswenipathak** [comment]
1. What should be the order?
2. I updated Docker and BioContainers instructions after carefully examining in search, what else should be updated?

**Comment by jpfeuffer** [comment]
@OpenMS/doc-team

**Comment by timosachsenberg** [comment]
hmm Linux is tricky. 
We mainly use conda or docker container on linux if we want to install it without GUI, right? E.g., for nextflow etc.
But for the full GUI experience you either need the debian packages or build it your own.
Maybe we need to explain this to the users as well
