### ISSUE TITLE
INI files layout broken

### ISSUE THREAD

**Issue by jcharkow** [OpenMS/OpenMS-docs#156]
## Description of the documentation bug

 The INI file layout is very messy in the new doxygen layout
E.g. https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_OpenSwathWorkflow.html
## Expected behaviour

Would expect layout to be more like previous version 
E.g. https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/2.8.0/html/UTILS_OpenSwathWorkflow.html

**Comment by jpfeuffer** [comment]
fixed
