### ISSUE TITLE
Idea: Use tabs for installation options? And/or platforms

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#17]
If you think it helps for UIX.

https://github.com/executablebooks/sphinx-tabs

**Comment by tapaswenipathak** [comment]
OpenMS-docs has markdown + readthedocs + furo. Quite a few customisations on headings and sidebars, doesn't work with this combination, I'll update.

**Comment by jpfeuffer** [comment]
That is sad. Maybe we should use rst then, if this happens more often and markdown is too limited.

**Comment by tapaswenipathak** [comment]
Then we have code/commands/syntax/formatting all over on GitHub in OpenMS-docs. Markdown should not be limited, there is no formatting command visible, till now in any file, on readthedocs, on GitHub, or in a PDF.

**Comment by jpfeuffer** [comment]
But you just said that tabs are not possible in Markdown, right?

**Comment by ghost** [comment]
Can we use a mix?

**Comment by tapaswenipathak** [comment]
this should do:

473529e709d20671af6a850e90019acba9b1c5f1.

i'm not sure how to provide the information in a shorter format.

<img width="1022" alt="Screenshot 2022-05-24 at 11 23 10 PM" src="https://user-images.githubusercontent.com/4143778/170100709-9498d074-bb74-46c4-9431-f6f10ade88c8.png">

**Comment by jpfeuffer** [comment]
Looks very good!

We could do a heading:
Installation on different platforms

Or sth like that. Then leave out "installation on"

**Comment by greengypsy** [comment]
I had a look at Rahul's work and I think it is possible to summarise what OpenMS is and what it is used for more clearly. It appears as though OpenMS is applied to more areas other than proteomics and metabolomics. Am I right?
