### ISSUE TITLE
URLs should be clickable

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#18]
All URLs should be links. Or be given a named link. E.g. pkgs.org on Linux installation instructions

changes to be done: https://github.com/OpenMS/OpenMS-docs/commit/c4c81281a98839243105df847344a77c0d1a0d72.

**Comment by jpfeuffer** [comment]
@tapaswenipathak I think we should use this:
https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#linkify

And probably some other markdown extensions

**Comment by tapaswenipathak** [comment]
this should do: https://github.com/OpenMS/OpenMS-docs/commit/c4c81281a98839243105df847344a77c0d1a0d72

**Comment by ghost** [comment]
I don't understand - what is the advantage of using linkify?

**Comment by jpfeuffer** [comment]
I think just that you don't need to do `[url](url)`

**Comment by tapaswenipathak** [comment]
@greengypsy can we close this?
