### ISSUE TITLE
Always specify lexers for code blocks

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#19]
https://pygments.org/docs/lexers/#lexers-for-various-shells

currently the highlighting is off

**Comment by ghost** [comment]
I think we need https://www.google.com/amp/s/www.freecodecamp.org/news/how-to-format-code-in-markdown/amp/

**Comment by jpfeuffer** [comment]
No, I think sphinx rst does it automatically. You just need to add the language that is inside a codeblock everytime.

**Comment by tapaswenipathak** [comment]
I added, can add; but then there would be a greenish background color:

<img width="714" alt="Screenshot 2022-05-19 at 9 31 14 PM" src="https://user-images.githubusercontent.com/4143778/169345583-e4236962-e2a4-4331-a7c9-0f5671796943.png">

Plus there is not a lot of code on openms.readthedocs.io, rn.

**Comment by jpfeuffer** [comment]
This can be styled with css or in the conf.py

**Comment by jpfeuffer** [comment]
By the way, i don't have a green background. Where did you get this from?

#22

**Comment by tapaswenipathak** [comment]
i don't think you have anything with that change.

see: https://staging-openms.readthedocs.io/en/staging/docs/installations/installation-on-gnu-linux.html

(the other code block at least have default highlighting.)

**Comment by jpfeuffer** [comment]
It does change. The "-" should not be highlighted as an operator.

It will have more impact on more complex scripts. We can write an adapted Lexer if we want to highlight e.g. sudo.

By the way, sudo is of course not always needed. But I guess people will know?

**Comment by ghost** [comment]
I'm not getting a green background... Is that something to do with furo?

**Comment by jpfeuffer** [comment]
Yes probably the green was in a non-furo theme.
Feel free to add the lexers to remaining code blocks. I am 100% sure that it is only beneficial

**Comment by ghost** [comment]
<img width="348" alt="Screen Shot 2022-05-20 at 5 36 04 pm" src="https://user-images.githubusercontent.com/31978630/169483511-f339aa73-4bd7-44dc-96ac-ad59de727ffb.png">

**Comment by ghost** [comment]
I think we need the **pygments _style** directive in the conf.py file to highlight syntax:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-pygments_style

**Comment by ghost** [comment]
<img width="498" alt="Screen Shot 2022-05-21 at 5 37 40 pm" src="https://user-images.githubusercontent.com/31978630/169642372-ceff2745-dc08-489c-a140-fd27bb722796.png">

**Comment by jpfeuffer** [comment]
Yes this is fine. Did you need pygments? I understood this should be active by default.

**Comment by ghost** [comment]
Yeah I needed pygments. I added the following line of code to the conf.py file:
`pygments_style = 'sas'`

There are other styles available here: https://pygments.org/styles/

**Comment by jpfeuffer** [comment]
Can you select a pygments_dark_style too please?

**Comment by tapaswenipathak** [comment]
Ref: https://github.com/OpenMS/OpenMS-docs/pull/30#issuecomment-1133884271.

**Comment by tapaswenipathak** [comment]
- [x] Update [contributing guidelines](https://github.com/OpenMS/OpenMS-docs/blob/staging/.github/CONTRIBUTING.md).

**Comment by tapaswenipathak** [comment]
79ce9fb35bfd398665e6f9b6cf2e38f4b8479384

```
pygments_style = "sphinx"
pygments_dark_style = "monokai"
```
![](https://media.discordapp.net/attachments/969233556788359228/979773657855426560/Screenshot_2022-05-27_at_9.20.01_PM.png?width=1740&height=1036)

![](https://media.discordapp.net/attachments/969233556788359228/979773746057474078/Screenshot_2022-05-27_at_9.20.59_PM.png?width=1732&height=1036)

**Comment by tapaswenipathak** [comment]
69d9a542341705462da745a14c1aa629be226179

```
pygments_style = "xcode"
pygments_dark_style = "rrt"
```

![](https://media.discordapp.net/attachments/969233556788359228/979340609041100810/Screenshot_2022-05-26_at_4.39.52_PM.png)

![](https://media.discordapp.net/attachments/969233556788359228/979340676263198761/Screenshot_2022-05-26_at_4.40.08_PM.png?width=1546&height=1037)

**Comment by tapaswenipathak** [comment]
default none:

![](https://media.discordapp.net/attachments/969233556788359228/979340868324581416/Screenshot_2022-05-26_at_4.40.44_PM.png)

![](https://media.discordapp.net/attachments/969233556788359228/979341082875818014/Screenshot_2022-05-26_at_4.41.27_PM.png)
