### ISSUE TITLE
https://openms.readthedocs.io/en/latest/tutorials-and-quickstart-guides/quickstart-guides.html only contains two links

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-docs#190]
## Read Existing Documentation

I have checked the following places for the error:

- [ ] [OpenMS Documentation Troubleshooting]()
- [ ] [OpenMS API Developer FAQs]()

## Create OpenMS Bug Report

I have created the bug report in OpenMS for any pipeline errors.

- [ ] [OpenMS Open Issues](https://github.com/OpenMS/OpenMS/issues)

## Description of the documentation bug

- [ ] I have attached screenshots of the incorrect documentation

## OpenMS Installation

- Version:

**Comment by axelwalter** [comment]
Having both user and contributors quick start guide in the tutorials section (which is intended for users) does not make sense.
Suggestion: Keep user quick start in tutorials section and move contributors quick start to the contributors section.

**Comment by axelwalter** [comment]
See PR #195
