### ISSUE TITLE
Handouts for training

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-docs#2]

**Comment by tapaswenipathak** [comment]
- The file being referred: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/handout.pdf.
- Build output can be found here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/output/.

**Comment by tapaswenipathak** [comment]
ref: https://github.com/OpenMS/OpenMS-docs/issues/133. closing.
