### ISSUE TITLE
Use correct admonitions

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#26]
The current style of Notes etc does not look nice. There must be a wrong use of admonitions. Please check how to do this correctly.

## Read Existing Documentation

I have checked the following places for the error:

- [ ] [OpenMS Documentation Troubleshooting]()
- [ ] [OpenMS API Developer FAQs]()

## Create OpenMS Bug Report

I have created the bug report in OpenMS for any pipeline errors.

- [ ] [OpenMS Open Issues](https://github.com/OpenMS/OpenMS/issues)

## Description of the documentation bug

- [ ] I have attached screenshots of the incorrect documentation

## OpenMS Installation

- Version:

**Comment by ghost** [comment]
How does this look?
<img width="794" alt="Screen Shot 2022-05-21 at 10 15 55 pm" src="https://user-images.githubusercontent.com/31978630/169652123-76d605ea-cc18-43ef-9e2a-90280aec458c.png">

**Comment by ghost** [comment]
https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#admonition-directives

**Comment by jpfeuffer** [comment]
Much better, thanks!

**Comment by tapaswenipathak** [comment]
Ref: https://github.com/OpenMS/OpenMS-docs/issues/28.

**Comment by tapaswenipathak** [comment]
Ref: https://github.com/OpenMS/OpenMS-docs/pull/30#issuecomment-1133884271.

**Comment by tapaswenipathak** [comment]
- Hint
- Important
- Note
- Warning
- Tip

**Comment by tapaswenipathak** [comment]
- [x] Update [contributing guidelines](https://github.com/OpenMS/OpenMS-docs/blob/staging/.github/CONTRIBUTING.md).

**Comment by tapaswenipathak** [comment]
> There is an alternative option for admonitions that render in Github also: 
https://www.markdownguide.org/hacks/#admonitions
[Hacks | Markdown Guide](https://www.markdownguide.org/hacks/)
Workarounds for things not officially supported by Markdown.

https://discord.com/channels/832282841836159006/969233556788359228/978459215716839464

+1.

**Comment by tapaswenipathak** [comment]
We're good with this:

https://github.com/OpenMS/OpenMS-docs/commit/c23dcf14231c3c73b27ff3eced65aad48c4e5903. 

(everywhere)
