### ISSUE TITLE
Make sure that back ticks are added to libraries, files, etc.

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#31]
There are many places in the documentation, where back ticks are missing. Libraries, files and anything code related needs to be between back ticks. For example at [this link](https://staging-openms.readthedocs.io/en/staging/docs/installations/installation-on-gnu-linux.html):
<img width="820" alt="Screen Shot 2022-05-23 at 8 58 35 am" src="https://user-images.githubusercontent.com/31978630/169720718-131c2ee7-4646-48c4-88bd-fec31f132c05.png">

**Comment by tapaswenipathak** [comment]
1. `backtick` (code specific) 
2. _italics_ (if we have a lot of occurrences on a single page) 
3. **bold** : context : proper noun
4. w/o any formatting
5. [link]() to the glossary

(use these wisely)

**Comment by tapaswenipathak** [comment]
- [x] Update [contributing guidelines](https://github.com/OpenMS/OpenMS-docs/blob/staging/.github/CONTRIBUTING.md).
