### ISSUE TITLE
Keyboard strokes should be formatted appropriately

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#32]
You can format keyboard strokes like so:
<kbd>DEL</kbd>
This should be added to the documentation.

This was discussed [here](https://discord.com/channels/832282841836159006/969233556788359228/976884979692867594).

**Comment by tapaswenipathak** [comment]
> github supports <kbd>F1</kbd>
would this also work with readthedocs markdown?
https://meta.askubuntu.com/questions/707/how-to-use-keyboard-icon-in-markdown

https://discord.com/channels/832282841836159006/969233556788359228/976884979692867594

**Comment by tapaswenipathak** [comment]
> https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-kbd

https://discord.com/channels/832282841836159006/969233556788359228/976885375463194634

**Comment by tapaswenipathak** [comment]
- [x] Update [contributing guidelines](https://github.com/OpenMS/OpenMS-docs/blob/staging/.github/CONTRIBUTING.md).

**Comment by ghost** [comment]
I'm pretty sure that readthedocs will render this correctly. We can check.

**Comment by tapaswenipathak** [comment]
We're good with this:

https://github.com/OpenMS/OpenMS-docs/commit/62e103b7b3ea5eddc2c4b5828452fc563527f742

(everywhere)
