### ISSUE TITLE
Images not rendering on installation-on-macos.md

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#37]
The images on the [this page](https://staging-openms.readthedocs.io/en/staging/docs/installations/installation-on-macos.html) aren't rendering properly.

**Comment by tapaswenipathak** [comment]
These are ok. They have the URLs of the main branch. We can make it work on staging. 

<img width="1281" alt="Screenshot 2022-05-25 at 6 35 45 PM" src="https://user-images.githubusercontent.com/4143778/170268736-3767a6d6-a194-44dc-b11c-34c305000571.png">
