### ISSUE TITLE
OpenMS Documentation Gets a New Home

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-docs#4]
This issue tracks:
1. Movement of [Doxygen pages](https://github.com/OpenMS/OpenMS/tree/develop/doc) to [OpenMS-docs](https://github.com/OpenMS/OpenMS-docs).
2. Movement of [Wiki Pages](https://github.com/OpenMS/OpenMS/wiki) to [OpenMS API Reference](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html), [OpenMS-docs](https://github.com/OpenMS/OpenMS-docs), and [pyopenms-docs](https://github.com/OpenMS/pyopenms-docs).
3. Addition of [Tutorials](https://github.com/OpenMS/Tutorials) to [OpenMS-docs](https://github.com/OpenMS/OpenMS-docs).
4. Addition of References in [OpenMS-docs](https://github.com/OpenMS/OpenMS-docs) and updated information present in:
    - [updateHMDB](https://github.com/OpenMS/updateHMDB)
    - [usage_plots](https://github.com/OpenMS/usage_plots)
    - [dockerfiles](https://github.com/OpenMS/dockerfiles)
    - [build-scripts](https://github.com/OpenMS/build-scripts)
    - [autowrap](https://github.com/OpenMS/autowrap)
    - [contrib](https://github.com/OpenMS/contrib)
    - [PDCommunityNodes](https://github.com/OpenMS/PDCommunityNodes)

**Comment by tapaswenipathak** [comment]
1. Installation instructions:
    - [x] [Installation on GNU/Linux](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_linux_bin.html)
         - [x] C in https://github.com/OpenMS/OpenMS-docs
         - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
    - [x] [Installation on MacOS](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_mac_bin.html)
         - [x] C in https://github.com/OpenMS/OpenMS-docs
         - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
    - [x] [Installation on Windows](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_win_bin.html)
         - [x] C in https://github.com/OpenMS/OpenMS-docs
         - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
2. Documentation:
   - [x] [User Quickstart Guide](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/Quickstart.html)
       - [x] C+U in https://github.com/OpenMS/OpenMS-docs
           - [ ] [www.openms.de/BUGS](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/www.openms.de/BUGS): Dead link
       - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
   - [x] [TOPP tutorial](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_tutorial.html)
       - [x] C in https://github.com/OpenMS/OpenMS-docs
       - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
   - [x] [TOPPAS tutorial](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPPAS_tutorial.html)
       - [x] C in https://github.com/OpenMS/OpenMS-docs
       - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
3. Misc:
     - [x] [Support](https://github.com/OpenMS/OpenMS/wiki#contact)
        - [x] C in https://github.com/OpenMS/OpenMS-docs
     - [x] [Github](https://github.com/OpenMS/OpenMS)
         - [x] C in https://github.com/OpenMS/OpenMS-docs
     - [x] [Gitter chat](https://gitter.im/OpenMS/OpenMS)
        - [x] C in https://github.com/OpenMS/OpenMS-docs
     - [x] [Mailing List](https://sourceforge.net/projects/open-ms/lists/open-ms-general)
        - [x] C in https://github.com/OpenMS/OpenMS-docs
     - [x] [FAQ](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/FAQ.html)
        - [x] C in https://github.com/OpenMS/OpenMS-docs
        - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
    - [x] [Known Issues](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/known_dev_bugs.html)
        - [x] ?
4. Development:
   - [x] [Developer FAQ (online)](https://github.com/OpenMS/OpenMS/wiki/Developer-FAQ)
        - [x] U in https://github.com/OpenMS/OpenMS/tree/develop/doc
5. Documentation:
   - [x] [Developer Python Quickstart Guide (online)](https://pyopenms.readthedocs.io/en/latest/index.html)
       - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
   - [x] [External Code using OpenMS](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/external_code.html)
       - [x] C+R+U in https://github.com/OpenMS/OpenMS-docs
       - [x] D from https://github.com/OpenMS/OpenMS/tree/develop/doc
6. OpenMS Wiki: https://github.com/OpenMS/OpenMS/wiki
     - [x] About
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki#about
     - [x] For Users
          - [x] C+R+U in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki#for_users
     - [x] Getting in Contact
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki#for_users
     - [x] Reporting Bugs/Issues
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] For Developers
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] [Adding your own tool to the TOPP suite](https://github.com/OpenMS/OpenMS/wiki/Adding-your-own-tool-to-the-TOPP-suite)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Build an installer and KNIME package from an own branch](https://github.com/OpenMS/OpenMS/wiki/Build-an-installer-and-KNIME-package-from-an-own-branch)
          - [x] C in https://github.com/OpenMS/OpenMS-docs: Quick Start Guide
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Build pyOpenMS on Windows](https://github.com/OpenMS/OpenMS/wiki/Build-pyOpenMS-on-Windows)
          - [x] C/U in https://github.com/OpenMS/pyopenms-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Build your own OpenMS KNIME package](https://github.com/OpenMS/OpenMS/wiki/Build-your-own-OpenMS-KNIME-package)
          - [x] C in https://github.com/OpenMS/OpenMS-docs: Quick Start Guide
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Building OpenMS](https://github.com/OpenMS/OpenMS/wiki/Building-OpenMS)
          - [x] C/U/Merge in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Code Examples](https://github.com/OpenMS/OpenMS/wiki/Code-Examples)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Coding conventions](https://github.com/OpenMS/OpenMS/wiki/Coding-conventions)
          - [x] C in https://github.com/OpenMS/OpenMS/tree/develop/doc
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Comparison Scripts](https://github.com/OpenMS/OpenMS/wiki/Comparison-Scripts)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Compiling with self built compilers and non default standard libraries](https://github.com/OpenMS/OpenMS/wiki/Compiling-with-self-built-compilers-and-non-default-standard-libraries)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [ConsensusMap and ConsensusFeature whitepaper](https://github.com/OpenMS/OpenMS/wiki/ConsensusMap-and-ConsensusFeature-whitepaper)
           - [x] C in https://github.com/OpenMS/OpenMS-docs
           - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Conversion Scripts](https://github.com/OpenMS/OpenMS/wiki/Conversion-Scripts)
           - [x] C in https://github.com/OpenMS/OpenMS-docs
           - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Cpp Guide](https://github.com/OpenMS/OpenMS/wiki/Cpp-Guide)
           - [x] C+U in https://github.com/OpenMS/OpenMS/tree/develop/doc
           - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Developer FAQ](https://github.com/OpenMS/OpenMS/wiki/Developer-FAQ)
          - [x] C+U in https://github.com/OpenMS/OpenMS/tree/develop/doc
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Developer Guidelines for adding new dependent libraries](https://github.com/OpenMS/OpenMS/wiki/Developer-Guidelines-for-adding-new-dependent-libraries)
          - [x] C+U in Developer Quick Start Guide in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Discussion: Classification of proteins and peptides and protein groups](https://github.com/OpenMS/OpenMS/wiki/Discussion:-Classification-of-proteins-and-peptides-and-protein-groups)
          - [x] C+U in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Exporting a KNIME workflow as a Docker container](https://github.com/OpenMS/OpenMS/wiki/Exporting-a-KNIME-workflow-as-a-Docker-container)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [External Tools](https://github.com/OpenMS/OpenMS/wiki/External-Tools)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [HowTo Write Commit Messages](https://github.com/OpenMS/OpenMS/wiki/HowTo---Write-Commit-Messages)
          - [x] C in https://github.com/OpenMS/OpenMS/tree/develop/doc
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [ ] [How to setup new agents for Jenkins](https://github.com/OpenMS/OpenMS/wiki/How-to-setup-new-agents-for-Jenkins)
          - [ ] U in **Jenkins** https://github.com/OpenMS/OpenMS/wiki
      - [ ] [Jenkins CI CD system](https://github.com/OpenMS/OpenMS/wiki/Jenkins-CI-CD-system)
           - [ ] U in **Jenkins** https://github.com/OpenMS/OpenMS/wiki
      - [x] [NewBuildUnit](https://github.com/OpenMS/OpenMS/wiki/NewBuildUnit)
           - [ ] C in https://github.com/OpenMS/OpenMS/wiki ?
      - [x] [OpenMS 2.0 Kernel Whitepaper](https://github.com/OpenMS/OpenMS/wiki/OpenMS-2.0-Kernel-Whitepaper)
           - [x] C in https://github.com/OpenMS/OpenMS-docs
           - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [OpenMS 2.0 Planing](https://github.com/OpenMS/OpenMS/wiki/OpenMS-2.0-Planing)
           - [ ] ?
      - [x] [OpenMS 2.0 Planing Interfaces MSExperiment](https://github.com/OpenMS/OpenMS/wiki/OpenMS-2.0-Planing-Interfaces-MSExperiment)
           - [ ] ?
      - [x] [OpenMS Docker Containers](https://github.com/OpenMS/OpenMS/wiki/OpenMS-Docker-Containers)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [OpenMS Git Workflow](https://github.com/OpenMS/OpenMS/wiki/OpenMS-Git-Workflow)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] U in https://github.com/OpenMS/OpenMS/wiki
      - [x] [OpenMS missing core functionality](https://github.com/OpenMS/OpenMS/wiki/OpenMS-missing-core-functionality)
          - [x] ?
      - [x] [OpenMS workflow parameters for Q Exactive](https://github.com/OpenMS/OpenMS/wiki/OpenMS-workflow-parameters-for-Q-Exactive)
          - [x] C in https://github.com/OpenMS/OpenMS-docs
          - [x] U in https://github.com/OpenMS/OpenMS/wiki
      - [x] [Preparation of a new OpenMS release](https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release)
         - [x] C in https://github.com/OpenMS/OpenMS-docs
         - [x] U in https://github.com/OpenMS/OpenMS/wiki
      - [x] [Preparation of OpenMS 2.3 release](https://github.com/OpenMS/OpenMS/wiki/Preparation-of-OpenMS-2.3-release)
         - [x] U in https://github.com/OpenMS/OpenMS/wiki
         - [x] U in https://github.com/OpenMS/OpenMS-docs
     - [x] [Pull Request Checklist](https://github.com/OpenMS/OpenMS/wiki/Pull-Request-Checklist)
        - [x] C in https://github.com/OpenMS/OpenMS-docs
        - [x] U in https://github.com/OpenMS/OpenMS/wiki
        - [x] U in https://github.com/OpenMS/OpenMS-docs
     - [x] [pyOpenMS](https://github.com/OpenMS/OpenMS/wiki/pyOpenMS)
        - [x] U in https://github.com/OpenMS/pyopenms-docs
        - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [ ] [Regarding notarization of the macOS dmg](https://github.com/OpenMS/OpenMS/wiki/Regarding-notarization-of-the-macOS-dmg)
        - [ ] C in https://github.com/OpenMS/OpenMS-docs
        - [ ] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] [Release Preparation](https://github.com/OpenMS/OpenMS/wiki/Release-Preparation)
        - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [ScreenCasts](https://github.com/OpenMS/OpenMS/wiki/ScreenCasts)
        - [x] ?
     - [x] [Supported Compilers](https://github.com/OpenMS/OpenMS/wiki/Supported-Compilers)
        - [x] C in https://github.com/OpenMS/OpenMS-docs
        - [x] D from https://github.com/OpenMS/OpenMS/wiki
      - [x] [Testing an OpenMS release candidate](https://github.com/OpenMS/OpenMS/wiki/Testing-an-OpenMS-release-candidate)
         - [x] C in https://github.com/OpenMS/OpenMS/tree/develop/doc
         - [x] U in https://github.com/OpenMS/OpenMS/wiki ?
     - [x] [Thirdparty dependencies](https://github.com/OpenMS/OpenMS/wiki/Thirdparty-dependencies)
        - [x] C+U in https://github.com/OpenMS/OpenMS-docs
        - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] [Update check](https://github.com/OpenMS/OpenMS/wiki/Update-check)
         - [x] C in https://github.com/OpenMS/OpenMS-docs
         - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] [Useful Scripts](https://github.com/OpenMS/OpenMS/wiki/Useful-Scripts)
         - [x] C+U in https://github.com/OpenMS/OpenMS-docs
         - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] [Workflow Collection](https://github.com/OpenMS/OpenMS/wiki/Workflow-Collection)
         - [x] C+U in https://github.com/OpenMS/OpenMS-docs
         - [x] D from https://github.com/OpenMS/OpenMS/wiki
     - [x] [Write tests](https://github.com/OpenMS/OpenMS/wiki/Write-tests)
        - [x] C in Developer Guide in https://github.com/OpenMS/OpenMS/tree/develop/doc
        - [x] D from https://github.com/OpenMS/OpenMS/wiki
7. Tutorials/Handouts: https://github.com/OpenMS/Tutorials
     - [ ] C+U in https://github.com/OpenMS/OpenMS-docs
     - [ ] D https://github.com/OpenMS/Tutorials
8. [updateHMDB](https://github.com/OpenMS/updateHMDB)
    - [ ] Reference in https://github.com/OpenMS/OpenMS-docs
    - [ ] U https://github.com/OpenMS/updateHMDB
9. [usage_plots](https://github.com/OpenMS/usage_plots) 
    - [ ] Reference in https://github.com/OpenMS/OpenMS-docs
    - [ ] U https://github.com/OpenMS/updateHMDB
10. [dockerfiles](https://github.com/OpenMS/dockerfiles) 
    - [ ] Reference in https://github.com/OpenMS/OpenMS-docs
    - [ ] U https://github.com/OpenMS/dockerfiles
11. [build-scripts](https://github.com/OpenMS/build-scripts)
     - [ ] Reference in https://github.com/OpenMS/OpenMS-docs
     - [ ] U https://github.com/OpenMS/build-scripts
12. [autowrap](https://github.com/OpenMS/autowrap)
    - [ ] Reference in https://github.com/OpenMS/OpenMS-docs
    - [ ] U https://github.com/OpenMS/autowrap
13. [contrib](https://github.com/OpenMS/contrib)
    - [ ] Reference in https://github.com/OpenMS/OpenMS-docs
    - [ ] U https://github.com/OpenMS/autowrap
14. [PDCommunityNodes](https://github.com/OpenMS/PDCommunityNodes)
    - [ ] C in https://github.com/OpenMS/OpenMS-docs
    - [ ] U+D in https://github.com/OpenMS/PDCommunityNodes


*Note: CRUD stands for Create | Replace | Update | Delete*

**Comment by jpfeuffer** [comment]
can we rename this issue? @timosachsenberg can you update your text?

**Comment by timosachsenberg** [comment]
Sure feel free to rename or update.

**Comment by tapaswenipathak** [comment]
cc @axelwalter @enetz @jpfeuffer @KyowonJeong @poshul @OpenMS/doc-team.

**Comment by jpfeuffer** [comment]
I thought we decided that internal discussions stay in the wiki?
E.g. Openms 2.0 kernel white paper and meeting summaries

**Comment by tapaswenipathak** [comment]
On Sat, May 14, 2022 at 3:01 PM Julianus Pfeuffer
***@***.***> wrote:
>
> I thought we decided that internal discussions stay in the wiki?
> E.g. Openms 2.0 kernel white paper and meeting summaries

I was thinking papers could go to OpenMS/OpenMS-docs, just not visible
on https://openms.readthedocs.io/en/latest/? Say,
`docs/research/whitepapers`.

Meeting summaries, I'll just see for any content and maybe add them
under one category in the wiki. Meeting summaries for sure remains in
the wiki.

**Comment by tapaswenipathak** [comment]
Monday (**A**nywhere **o**n **E**arth) end of day, https://github.com/OpenMS/OpenMS-docs/compare/main...staging will be created, **please** make some time available for reviewing till Friday (AoE).

OpenMS Documentation: https://staging-openms.readthedocs.io/en/staging.
