### ISSUE TITLE
Some definitions in the glossary need to be reviewed

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#66]
For example:
<img width="753" alt="Screen Shot 2022-05-31 at 7 38 43 pm" src="https://user-images.githubusercontent.com/31978630/171149781-f6c75683-3b1f-446c-a184-9c4b83a54019.png">
Could be: A sequence of tools run on input data such as an mzML file which produces an output. There are over 185 TOPP tools to choose from.

<img width="333" alt="Screen Shot 2022-05-31 at 7 40 33 pm" src="https://user-images.githubusercontent.com/31978630/171150089-07bf064a-ced4-4828-9eed-35a3f9dcc7b1.png">
Could be: TOPP is an application built using OpenMS. TOPP consists of many tools.

<img width="558" alt="Screen Shot 2022-05-31 at 7 41 52 pm" src="https://user-images.githubusercontent.com/31978630/171150312-2d5cf8e2-6fa1-43d0-b9b6-a4e329eafe73.png">
Could be: TOPPAS is an application which provides a GUI to create, edit and apply TOPP tools. TOPPAS is no longer supported and has been replaced by KNIME.

**Comment by jpfeuffer** [comment]
Also TOPPAS is only an ".app" on macOS, so maybe remove ".app"
