### ISSUE TITLE
Possible restructuring of documentation

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#67]
This is how I think the documentation could be structured:

Introduction
- What is OpenMS
- Background

Getting Started
- Installation on GNU/Linux
- Installation on macOS
- Installation on Windows

Quick Start Guides
- User Quick Start Guide
- Contributor Quick Start Guide

TOPP
- What is TOPP
- Key Concepts
- TOP tools
   -  Graphical tools
   -  File handling tools
   -  Signal processing and preprocessing tools
   -  Quanitation tools
   -  Map Alignment tools
   -  Protein/Peptide identification tools
   -  etc
   
KNIME
- What is KNIME
- User interface
- Examples
   
TOPPAS
- What is TOPPAS
- User Interface
- Examples

Tutorials 
- TOPP
- KNIME
- TOPPAS

Developer Resources
- Developer guidelines for adding new dependency libraries
- Link external code to OpenMS
- Custom compilation of OpenMS
- Build custom KNIME application
- Add new tool to the TOP suite

Additional Resources
- OpenMS git workflow
- Reporting bugs and issues
- Write and label github issues
- Pull request checklist

Downloads
- OpenMS installers
- Workflows
- OpenMS releases
- Other resources

Quick Reference
- Contributor FAQ
- Developer FAQ
- Glossary
- Contact Us

@tapaswenipathak  @jpfeuffer would be great to hear your thoughts.

**Comment by jpfeuffer** [comment]
Awesome. I would sign that.

The only thing to question is if we should even still provide tutorials for TOPPAS prominently (since it is deprecated)

**Comment by KyowonJeong** [comment]
Exactly. I also thought about how to deal with TOPPAS.
I would add "Where is/has been OpenMS being used" for a bit of advertisement unless it is already included.. I believe it is somewhere, but could not find this in the current intro page. Just my opinion though.

**Comment by tapaswenipathak** [comment]
closing: dup: https://github.com/OpenMS/OpenMS-docs/issues/59/.

**Comment by tapaswenipathak** [comment]
(for further discussion, please feel free to be writing in the linked issue).
