### ISSUE TITLE
Add tooltips to glossary terms

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#68]
It would be nice to add tooltips to glossary terms, so that people don't have to navigate away from the page to find a definition.

Resources include:
- https://sphinx-hoverxref.readthedocs.io/en/latest/usage.html#tooltip-on-glossary-terms
- https://myst-parser.readthedocs.io/en/latest/syntax/roles-and-directives.html#roles-an-in-line-extension-point
- https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_roles

**Comment by matteopilz** [comment]
As this issue also addresses the glossary in a similar way as [this one](https://github.com/OpenMS/OpenMS-docs/issues/86), maybe it would be best to close it and rename the other one.
