### ISSUE TITLE
Add broken/dead links check for markdown

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#72]
## Is your feature request related to a OpenMS API Reference Documentation? Please describe.

No, maintenance automation.

- [x] I have attached screenshot describing the problem, if applicable.

## Describe the documentation enhancement you'd like
Add automated link/URL check for broken or dead links.

## Describe alternatives you've considered

This looks like a good GitHub action: https://github.com/marketplace/actions/markdown-link-check.

## Additional context

Would you be interested in adding this GitHub action? @greengypsy

**Comment by ghost** [comment]
@tapaswenipathak I'll look into it

**Comment by tapaswenipathak** [comment]
Closed via https://github.com/OpenMS/OpenMS-docs/pull/114.
