### ISSUE TITLE
Make sure every line in documentation has a (max) line length of 120 characters

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#73]
## Is your feature request related to a OpenMS API Reference Documentation? Please describe.

No, cleanup.

- [x] I have attached screenshot describing the problem, if applicable.

## Describe the documentation enhancement you'd like

Right now, the lines are of varying lengths. Red vertical line is at 120 characters. 

<img width="1274" alt="Screenshot 2022-06-07 at 8 18 55 PM" src="https://user-images.githubusercontent.com/4143778/172411004-b7acfffc-579d-4f96-b402-35295bd8dc9c.png">

## Describe alternatives you've considered

There should be some GitHub action, plugin, or something to automate this; if not, do it manually for consistency.

**Comment by Harixomxsingh** [comment]
hey there, i am interest with this issue

**Comment by Jigidy** [comment]
Hello there,

I've started working on this project. I am assuming that all of the docs need this clean-up. If all of the docs do not need this clean-up that is well and good, but I'm presuming that we want everything to be universal. If this is not correct, let me know or just deny the merge and I'll move on. 

I'll get at least one or two in a day, if not more. Any questions, just ask.

- Julian

**Comment by tapaswenipathak** [comment]
> I've started working on this project. I am assuming that all of the docs need this clean-up. If all of the docs do not need this clean-up that is well and good, but I'm presuming that we want everything to be universal. If this is not correct, let me know or just deny the merge and I'll move on.

everywhere, yes. I'm available here: https://discord.com/invite/wcWETcAkvS for any questions you may have.
