### ISSUE TITLE
Define "single layers" in the documentation?

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#76]
<img width="929" alt="Screenshot 2022-06-07 at 9 04 47 PM" src="https://user-images.githubusercontent.com/4143778/172421772-4e24ff6d-e6c9-47fe-aae0-8177f766b357.png">

This issue can be used as a tracker to close the point raised in the review of PR https://github.com/OpenMS/OpenMS-docs/pull/65.

**Comment by ghost** [comment]
I still don't really understand the concept of layers. In photoshop, you have the option of grouping objects and then applying effects to that particular group. I'm not really sure how that applies to a spectra. Is it possible to say, group different peaks?

**Comment by jpfeuffer** [comment]
No, really layers. Lowest layer are the spectra which produce dots on the canvas.
Then you can have another layer of spectra to check for differences (we do not support opacity yet though).
Or you can have layers of features which produce rectangles on top of the dots/peaks to show that a feature was found there.
Or a layer of mass traces that will add lines on top of the peaks.
Etc..

**Comment by ghost** [comment]
So as far as I understand, in a spectra you have peaks, where each peak represents a fragmented molecule/ion. Based on the fragment m/z values and where they are located, you can work out what the original molecule is, prior to being analysed.

I don't really understand where the mass traces come in. I've had a read of Timo's thesis and I'm still lost.

**Comment by timosachsenberg** [comment]
If you stack these spectra on top of each other you get something similar to a 2D image.
Because an ion appears at a certain time and then disappears again (= it elutes over some time span) you will observe the same mass (or actually m/z value) for that ion givin rise to a trace in this 2D image.

**Comment by tapaswenipathak** [comment]
On Wed, Jun 8, 2022 at 1:50 PM Julianus Pfeuffer
***@***.***> wrote:
>
> No, really layers. Lowest layer are the spectra which produce dots on the canvas.
> Then you can have another layer of spectra to check for differences (we do not support opacity yet though).
> Or you can have layers of features which produce rectangles on top of the dots/peaks to show that a feature was found there.
> Or a layer of mass traces that will add lines on top of the peaks.
> Etc..

anything else? :)
