### ISSUE TITLE
Rethink and write UTILS introductory definition for the user quick start guide

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#79]
> In the user quick start guide I think our definition of UTILS is a bit outdated. By now, we include experimental, little tested tools there as well.

Ref https://github.com/OpenMS/OpenMS-docs/pull/65#issuecomment-1146649107.

**Comment by tapaswenipathak** [comment]
> Besides TOPP, OpenMS offers a range of other tools. They are not included in TOPP as they are not part of typical analysis pipelines, but they still might be very helpful to you.
> Just as the TOPP tools, they can be found in the OpenMS/bin folder.
> The UTILS tools are divided into several subgroups:

I think is the only introductory definition and is very dependent. 

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_documentation.html

**Comment by jpfeuffer** [comment]
This one is already a bit better than the one in the docs but not perfect.

**Comment by tapaswenipathak** [comment]
On Wed, Jun 8, 2022 at 1:38 PM Julianus Pfeuffer
***@***.***> wrote:
>
> This one is already a bit better than the one in the docs but not perfect.

I require content lines.
