### ISSUE TITLE
User quickstart guide (e.g., command line examples -> transition to other handouts)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS-docs#8]

**Comment by tapaswenipathak** [comment]
- The file being referred: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/handout.pdf.
- Build output can be found here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/output/.

**Comment by tapaswenipathak** [comment]
What is/are the todo(s)?

**Comment by timosachsenberg** [comment]
I think just in general having a user quickstart guide that links to the different tutorials

**Comment by tapaswenipathak** [comment]
https://openms.readthedocs.io/en/develop has the following tuts
- TOPP tut
- TOPPAS tut
- KNIME tut
- User tut: ref: https://github.com/OpenMS/OpenMS-docs/pull/52.


Please create a new ticket to let me know which tut should be linked or added.

Ref: https://github.com/OpenMS/Tutorials/issues/205; closing.
