### ISSUE TITLE
Decide what part of UTILs documentation should be added to openms.readthedocs.io (if)

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#81]
https://github.com/OpenMS/OpenMS-docs/pull/65#issuecomment-1146649107.

Ref: 
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_documentation.html
- <img width="682" alt="Screenshot 2022-06-08 at 7 37 10 AM" src="https://user-images.githubusercontent.com/4143778/172515829-99ca1163-4609-4c59-85b3-e096215ce51a.png">

**Comment by jpfeuffer** [comment]
I think for now UTILS should be exactly handled like TOPP. Just with another overall description. Currently we use them more as a collection of helper tools or untested tools.

**Comment by tapaswenipathak** [comment]
On Wed, Jun 8, 2022 at 1:42 PM Julianus Pfeuffer
***@***.***> wrote:
>
> I think for now UTILS should be exactly handled like TOPP. Just with another overall description. Currently we use them more as a collection of helper tools or untested tools.

1. there is no UTILS tut.
2. there are no introductory UTILS docs that can be added to
openms.readthedocs.io.
3. other than one-line description of UTILS, redirecting to UTILS API
reference, there is nothing substantial in openms.readthedocs.io about
UTILS.

**Comment by jpfeuffer** [comment]
That's why we should mention them together with TOPP so that people treat them almost equally.
I.e. whenever one links to TOPP tools, also link to UTIL tools.
