### ISSUE TITLE
Add images to or change the text colour of the glossary term links

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#86]
At the moment, the glossary term links are difficult to distinguish. By adding an image or changing the text colour, this will help them stand out.

**Comment by jpfeuffer** [comment]
IMHO the best options are:
- superscript info icon
- dotted underline and greyish text

**Comment by tapaswenipathak** [comment]
Every tooltip is shown with a dotted underline and blue color text (which goes with the theme), for smooth reading transition, closing.

<img width="804" alt="Screenshot 2022-06-10 at 6 12 22 PM" src="https://user-images.githubusercontent.com/4143778/173066692-cd7c5dd9-7934-46ac-b586-5e7962bb9aff.png">
