### ISSUE TITLE
openms.readthedocs.io doesn't show develop branch

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS-docs#88]
I think OpenMS readthedocs requires a resync [GitHub incoming webhook](https://readthedocs.org/dashboard/staging-openms/integrations/200802/) integration, I don't have the auth.

<img width="1550" alt="Screenshot 2022-06-10 at 6 36 39 PM" src="https://user-images.githubusercontent.com/4143778/173071116-04120111-f47d-49b3-8dd5-5db17bb0fdc0.png">
 

<img width="1550" alt="Screenshot 2022-06-10 at 6 36 30 PM" src="https://user-images.githubusercontent.com/4143778/173070986-63429ac7-01a2-4c0d-8584-0bbdd7cacd56.png">

(tasks gets lost in discord, will use issues from now on)

**Comment by timosachsenberg** [comment]
I clicked on resync webhook. Does this do the job?

**Comment by tapaswenipathak** [comment]
i see two now, `develop` branch appears.

(might require a cleanup)

<img width="996" alt="Screenshot 2022-06-10 at 6 56 26 PM" src="https://user-images.githubusercontent.com/4143778/173075320-4b80631b-c40d-4dad-9e29-73c8c68c548b.png">
