### ISSUE TITLE
Use of variable for the current version number

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#91]
## Is your feature request related to a OpenMS API Reference Documentation? Please describe.

Would be nice if we used fixed version numbers in the docs, such that older docs still point to older releases in the install instructions.
This is only maintainable with variables. I bet this is easily possible with sphinx.

- [ ] I have attached screenshot describing the problem, if applicable.

**Comment by ghost** [comment]
https://sphinxcontrib-versioning.readthedocs.io/en/latest/tutorial.html

**Comment by jpfeuffer** [comment]
> https://sphinxcontrib-versioning.readthedocs.io/en/latest/tutorial.html

Maybe that is even overkill since we use readthedocs.
https://docs.readthedocs.io/en/stable/environment-variables.html
And then https://stackoverflow.com/questions/34006784/how-do-i-access-a-variable-in-sphinx-conf-py-from-my-rst-file

**Comment by tapaswenipathak** [comment]
What is the use case of having `{version}` variable? What enhancement(s) does it bring in maintenance? 

(we discussed, i know now, missed thinking on a few points.)
