### ISSUE TITLE
Restructure installation instructions

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#92]
## Is your feature request related to a OpenMS API Reference Documentation? Please describe.

Container actually work on ALL platforms. I think this should be an own section like "Build from source"

- [ ] I have attached screenshot describing the problem, if applicable.

**Comment by tapaswenipathak** [comment]
dup: https://github.com/OpenMS/OpenMS-docs/issues/98, closing.
