### ISSUE TITLE
Internal links broken

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#93]
Due to nasty upstream bug https://github.com/executablebooks/MyST-Parser/issues/564

## Read Existing Documentation

I have checked the following places for the error:

- [ ] [OpenMS Documentation Troubleshooting]()
- [ ] [OpenMS API Developer FAQs]()

## Create OpenMS Bug Report

I have created the bug report in OpenMS for any pipeline errors.

- [ ] [OpenMS Open Issues](https://github.com/OpenMS/OpenMS/issues)

## Description of the documentation bug

- [ ] I have attached screenshots of the incorrect documentation

## OpenMS Installation

- Version:

**Comment by ghost** [comment]
<img width="1427" alt="Screen Shot 2022-06-12 at 2 54 12 pm" src="https://user-images.githubusercontent.com/31978630/173217037-dfc31bb8-81d5-40fe-9a73-39bc852ca66e.png">

Do we need to manually insert html <a> tags into the markdown files?

**Comment by jpfeuffer** [comment]
I have no idea. It should work out of the box.
Someone should fix #94 before we continue here. Otherwise we cannot complain upstream.
