### ISSUE TITLE
Dozens of warnings

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#94]
https://readthedocs.org/projects/staging-openms/builds/17157418/

No explanation needed.

## Read Existing Documentation

I have checked the following places for the error:

- [ ] [OpenMS Documentation Troubleshooting]()
- [ ] [OpenMS API Developer FAQs]()

## Create OpenMS Bug Report

I have created the bug report in OpenMS for any pipeline errors.

- [ ] [OpenMS Open Issues](https://github.com/OpenMS/OpenMS/issues)

## Description of the documentation bug

- [ ] I have attached screenshots of the incorrect documentation

## OpenMS Installation

- Version:

**Comment by jpfeuffer** [comment]
I will switch to warning = error.

**Comment by tapaswenipathak** [comment]
dup: https://github.com/OpenMS/OpenMS-docs/issues/93.

**Comment by jpfeuffer** [comment]
The warnings about links are only a part of our many warnings!
