### ISSUE TITLE
Tabs not rendering properly on Introduction page

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS-docs#96]
<img width="810" alt="Screen Shot 2022-06-13 at 10 52 18 am" src="https://user-images.githubusercontent.com/31978630/173263310-5e76acf1-9491-4dc4-9a1e-f46212f71c4e.png">
This is located at: https://openms.readthedocs.io/en/develop/docs/introduction.html

**Comment by tapaswenipathak** [comment]
closed by https://github.com/OpenMS/OpenMS-docs/pull/105/commits/c835aa01e6ba3280ee955642681d128c973f8e2f.
