### ISSUE TITLE
Installation instructions wrong

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-docs#98]
Especially everything that has to do with docker and conda.

## Read Existing Documentation

I have checked the following places for the error:

- [ ] [OpenMS Documentation Troubleshooting]()
- [ ] [OpenMS API Developer FAQs]()

## Create OpenMS Bug Report

I have created the bug report in OpenMS for any pipeline errors.

- [ ] [OpenMS Open Issues](https://github.com/OpenMS/OpenMS/issues)

## Description of the documentation bug

- [ ] I have attached screenshots of the incorrect documentation

## OpenMS Installation

- Version:

**Comment by jpfeuffer** [comment]
I tried to fix it but my PR was reverted so someone else needs to fix it.

**Comment by tapaswenipathak** [comment]
dup: https://github.com/OpenMS/OpenMS-docs/issues/130, closing.
